integerValue1: 1
integerValue2: 2
integerValue3: 3
integerValue4: 4
booleanValue1: false
booleanValue2: true
booleanValue3: false
booleanValue4: true
booleanValue5: false
booleanValue6: true
booleanValue7: false
booleanValue8: true
innerTestConfig:
  integerValue: 10
  booleanValue: true
